export const AdminServices=[
    {
    id:0,
    requestDate:'02/04/2023',
    serviceName:'Tyre Change',
    customerName:'Nouman',
    customerAdress:'Islamabad',
    time:'10:00am',
    completed: 'pending',
    technician: 'Adnan',
    description:'There is A puncture in the left back tyre'
    },
    {
    id:1,
    requestDate:'01/04/2023',
    serviceName:'Car Tunning',
    customerName:'Ahmed',
    customerAdress:'Rawalpindi',
    time:'11:00am',
    completed: 'pending',
    technician: 'Adnan',
    description:'  '
    },
    {
    id:2,
    requestDate:'30/03/2023',
    serviceName:'Oil Change',
    customerName:'Hammad',
    customerAdress:'RawalPindi Shamsabad',
    time:'02:00pm',
    description:'  ',
    completed: 'pending',
    technician: 'Adnan',
    },
    {
    id:3,
    requestDate:'01/04/2023',
    serviceName:'Engine Fix',
    customerName:'Aqib',
    customerAdress:' Saddar Rawalpindi',
    time:'04:00pm',
    description:'  ',
    completed: 'pending',
    technician: 'Adnan',
    },
    {
    id:4,
    requestDate:'02/04/2023',
    serviceName:'Car Wash',
    customerName:'Hamza',
    customerAdress:'6th Road Rawalpindi',
    time:'01:00pm',
    description:'  ',
    completed: 'pending',
    technician: 'Adnan',
    },
    ]